on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test the action

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pusher trigger test
        uses: ./
        with:
          app-id: $PUSHER_APP_ID
          app-key: $PUSHER_APP_KEY
          app-secret: $PUSHER_APP_SECRET
          app-cluster: eu
          channel: global
          event: push-trigger-event
          message: "{text:'Pushed from CI ${{github.sha}}'}"
